sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t matthewtyas/react-test -f ./client/Dockerfile.dev ./client

after_success:
  - docker build -t matthewtyas/multi-client ./client
  - docker build -t matthewtyas/multi-nginx ./nginx
  - docker build -t matthewtyas/multi-server ./server
  - docker build -t matthewtyas/multi-worker ./worker
  # Take images and deploy them to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push matthewtyas/multi-client
  - docker push matthewtyas/multi-nginx
  - docker push matthewtyas/multi-server
  - docker push matthewtyas/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-north-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-north-1-945398490524
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY